version: "3.8"
services:
  node:
    build:
      dockerfile_inline: |
        FROM node:18-alpine
        WORKDIR /app
        RUN npm create vite@latest . -- --template react-swc-ts && echo y
    # user: "node"
    image: "node18:vite"
    working_dir: /app
    container_name: vite
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - NODE_ENV=development
    # volumes:
    #   - ./src:/home/node/app
    ports:
      - 5173:5173
    # command: 
    stdin_open: true
    tty: true
