version: "3.8"
services:
  node:
    build:
      dockerfile_inline: |
        FROM node:18-alpine
        WORKDIR /app
        RUN npm create vite@latest . -- --template react-swc-ts && echo y && npm install
        RUN echo 'import { defineConfig } from "vite";\
            import react from "@vitejs/plugin-react-swc";\
            export default defineConfig({\
              plugins: [react()],\
              server: {\
                watch: {\
                  usePolling: true,\
                },\
                host: true,\
                strictPort: true,\
                port: 5173,\
              },\
            });' > vite.config.ts

    # ENTRYPOINT [ "npm", "run" ]
    # user: "node"
    image: node18:vite
    working_dir: /app
    container_name: $npm_package_config_container
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - NODE_ENV=development
    volumes:
      - ./$npm_package_config_container/app:/app
      # - /app/node_modules
    ports:
      - 5173:5173
    # command: ["npm","run","dev"]
    stdin_open: true
    tty: true
